In [56]:
import pandas as pd

# 构造DataFrame----创建数据集(lol排名信息)
lol_rank = pd.DataFrame(
    [
        # 1	LOVE3001#lolxd	Challenger	1543	万花通灵/琴瑟仙女/牛头酋长	165	354/263	57%
        {"排名": 1, "召唤师": "LOVE3001#lolxd", "段位": "challenger",
            "LP": 1543, "常用英雄": ["万花通灵", "琴瑟仙女", "牛头酋长"], "胜率": 0.57},
        # 2	Berik#haru	Challenger	1400	刀锋之影/傲之追猎者/破败之王	950	275/198	58%
        {"排名": 2, "召唤师": "Berik#haru", "段位": "challenger", "LP": 1400,
            "常用英雄": ["刀锋之影", "傲之追猎者", "破败之王"], "胜率": 0.58},
        # 3	TWITCH ELOSANTA#1111	Challenger	1400	死亡颂唱者/复仇焰魂/赏金猎人	550	214/149	59%
        {"排名": 3, "召唤师": "TWITCH ELOSANTA#1111", "段位": "challenger",
            "LP": 1400, "常用英雄": ["死亡颂唱者", "复仇焰魂", "赏金猎人"], "胜率": 0.59},
        # 4	我依然是世一上#我不骗人	Challenger	1288	无双剑姬/机械公敌/铁血狼母	129	300/169	64%
        {"排名": 4, "召唤师": "我依然是世一上#我不骗人", "段位": "challenger",
            "LP": 1288, "常用英雄": ["无双剑姬", "机械公敌", "铁血狼母"], "胜率": 0.64},
        # 5	Dun#NA1	Challenger	1242	奥术先驱/暗黑元首/惩戒之箭	539	296/224	57%
        {"排名": 5, "召唤师": "Dun#NA1", "段位": "challenger", "LP": 1242,
            "常用英雄": ["奥术先驱", "暗黑元首", "惩戒之箭"], "胜率": 0.57},
        # 6	LP Yoinker XD#NA1	Challenger	1222	永猎双子/虚空掠夺者/涤魂圣枪	289	153/74	67%
        {"排名": 6, "召唤师": "LP Yoinker XD#NA1", "段位": "challenger",
            "LP": 1222, "常用英雄": ["永猎双子", "虚空掠夺者", "涤魂圣枪"], "胜率": 0.67},
        # 7	huncho#RANK1	Challenger	1199	铁血狼母/战争之影/法外狂徒	306	229/151	60%
        {"排名": 7, "召唤师": "huncho#RANK1", "段位": "challenger",
            "LP": 1199, "常用英雄": ["铁血狼母", "战争之影", "法外狂徒"], "胜率": 0.6},
        # 8	MunchyPunchyLOL#TTV1	Challenger	1168	无极剑圣/傲之追猎者/德玛西亚皇子	828	199/144	58%
        {"排名": 8, "召唤师": "MunchyPunchyLOL#TTV1", "段位": "challenger", "LP": 1168,
            "常用英雄": ["无极剑圣", "傲之追猎者", "德玛西亚皇子"], "胜率": 0.58},
        # 9	EDG Viper#NA11	Challenger	1155	圣枪游侠/祖安花火/探险家	51	160/74	68%
        {"排名": 9, "召唤师": "EDG Viper#NA11", "段位": "challenger", "LP": 1155,
            "常用英雄": ["圣枪游侠", "祖安花火", "探险家"], "胜率": 0.68},
        # 10	Feint#7993	Challenger	1130	不破之誓/探险家/戏命师	747	464/462	50%
        {"排名": 10, "召唤师": "Feint#7993", "段位": "challenger", "LP": 1130,
            "常用英雄": ["不破之誓", "探险家", "戏命师"], "胜率": 0.5}
    ]
)
lol_rank
# f"{lol_rank['LP'].mean():.2f}"

   排名                   召唤师          段位    LP                   常用英雄    胜率
0   1        LOVE3001#lolxd  challenger  1543     [万花通灵, 琴瑟仙女, 牛头酋长]  0.57
1   2            Berik#haru  challenger  1400    [刀锋之影, 傲之追猎者, 破败之王]  0.58
2   3  TWITCH ELOSANTA#1111  challenger  1400    [死亡颂唱者, 复仇焰魂, 赏金猎人]  0.59
3   4          我依然是世一上#我不骗人  challenger  1288     [无双剑姬, 机械公敌, 铁血狼母]  0.64
4   5               Dun#NA1  challenger  1242     [奥术先驱, 暗黑元首, 惩戒之箭]  0.57
5   6     LP Yoinker XD#NA1  challenger  1222    [永猎双子, 虚空掠夺者, 涤魂圣枪]  0.67
6   7          huncho#RANK1  challenger  1199     [铁血狼母, 战争之影, 法外狂徒]  0.60
7   8  MunchyPunchyLOL#TTV1  challenger  1168  [无极剑圣, 傲之追猎者, 德玛西亚皇子]  0.58
8   9        EDG Viper#NA11  challenger  1155      [圣枪游侠, 祖安花火, 探险家]  0.68
9  10            Feint#7993  challenger  1130       [不破之誓, 探险家, 戏命师]  0.50

In [3]:
# 姓名  语文  数学  英语
# 张三  90  80  95
# 李四  85  90  88
# 王五  95  85  92

# import pandas as pd
# 构建DataFrame的方法
# 1. 从字典列表构建
df1 = pd.DataFrame(
    [
        {"姓名": "张三", "语文": 90, "数学": 80, "英语": 95},
        {"姓名": "李四", "语文": 85, "数学": 90, "英语": 88},
        {"姓名": "王五", "语文": 95, "数学": 85, "英语": 92}
    ]
)
# 2. 从字典构建
df2 = pd.DataFrame(
    {
        "姓名": ["张三", "李四", "王五"],
        "语文": [90, 85, 95],
        "数学": [80, 90, 85],
        "英语": [95, 88, 92]
    }
)
# 3. 元组列表构建
df3 = pd.DataFrame(
    [
        ("张三", 90, 80, 95),
        ("李四", 85, 90, 88),
        ("王五", 95, 85, 92)
    ],
    columns=["姓名", "语文", "数学", "英语"],    # 自定义列名/表头
    index=["a", "b", "c"]    # 自定义行索引
)
# 4. 列表构建
df4 = pd.DataFrame(
    [
        ["张三", 90, 80, 95],
        ["李四", 85, 90, 88],
        ["王五", 95, 85, 92]
    ],
    columns=["姓名", "语文", "数学", "英语"],    # 自定义列名/表头
    index=["a", "b", "c"],    # 自定义行索引
)
# 方法:
# 常见属性: index, columns, values, dtypes, size, shape
print('-'*50)
print(df1.index)        # 获取行索引----------> Series
print(df1.columns)      # 获取列索引----------> Series
print(df1.values)       # 获取所有值----------> [行列表，行列表，...]
print('-'*50)
# dataframe.属性.tolist() ----> 值的列表
print(df1.index.tolist())
print(df1.columns.tolist())
print(df1.values.tolist())


# print(df1.dtypes)       # 获取每一列的类型-----> 列名 元素类型 \n
# print(df1.size)         # 获取元素个数--------> 行数*列数 (仅计算值)
# print(df1.shape)        # 获取行数和列数-------> 元组:(行数, 列数)


# 对于series也适用上述部分方法

--------------------------------------------------
RangeIndex(start=0, stop=3, step=1)
Index(['姓名', '语文', '数学', '英语'], dtype='str')
[['张三' 90 80 95]
 ['李四' 85 90 88]
 ['王五' 95 85 92]]
--------------------------------------------------
[0, 1, 2]
['姓名', '语文', '数学', '英语']
[['张三', 90, 80, 95], ['李四', 85, 90, 88], ['王五', 95, 85, 92]]

In [ ]:
# Pandas数据的读取和写入
# read_XXXX     读取xxxx数据
# to_XXXX       写入xxxx数据
# import pandas as pd
df = pd.read_csv('Data/opgg_tier.csv')
df
# df['总场数'] = df['胜场'] + df['负场']

# # 调整列顺序
insert_tag = df.columns.tolist().index('胜场')
df.insert(insert_tag, '总场数', df['胜场'] + df['负场'])
# df = df[['#', '召唤师', 'LP', '胜场', '负场', '总场数', '胜率']]
# # 调整列名
col_names_list = df.columns.tolist()
col_names_list[df.columns.get_loc('#')] = '排名'
df.columns = col_names_list
df.to_csv('Data/opgg_tier_adjust.csv', index=False)  # 参数：（文件名路径，index是否包含索引）
df

,排名,召唤师,段位,LP,常用英雄,等级,总场数,胜场,负场,胜率
0,1,LOVE3001#lolxd,Challenger,1543,万花通灵/琴瑟仙女/牛头酋长,165,617,354,263,57%
1,2,Berik#haru,Challenger,1400,刀锋之影/傲之追猎者/破败之王,950,473,275,198,58%
2,3,TWITCH ELOSANTA#1111,Challenger,1400,死亡颂唱者/复仇焰魂/赏金猎人,550,363,214,149,59%
3,4,我依然是世一上#我不骗人,Challenger,1288,无双剑姬/机械公敌/铁血狼母,129,469,300,169,64%
4,5,Dun#NA1,Challenger,1242,奥术先驱/暗黑元首/惩戒之箭,539,520,296,224,57%
...,...,...,...,...,...,...,...,...,...,...
95,96,cyw#NA1,Challenger,828,虚空之眼/皮城女警/潮汐海灵,461,218,139,79,64%
96,97,Boybebui#NA1,Challenger,827,翠神/探险家/唤潮鲛姬,53,252,160,92,63%
97,98,宿命敲#lumi,Challenger,826,暴走萝莉/探险家/皮城女警,106,206,125,81,61%
98,99,Flow#THZ,Challenger,826,发条魔灵/沙漠皇帝/冰晶凤凰,1141,587,308,279,52%
99,100,Omi#Brooo,Challenger,826,虚空之女/戏命师/探险家,362,331,198,133,60%

In [5]:
# 数据的查看、选择、筛选


N = 5
# 查看前N行
df.head(N)
# 查看后N行
df.tail(N)
# # 数值列的统计信息(默认包含所有数值列,数量,均值,中位数,最小值,最大值,标准差)
df.describe()
# # 查看数据信息(列名、非空计数、数据类型等)
df.info()
# # 属性,查看列名
df.columns


df.head(N)

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   排名      100 non-null    int64
 1   召唤师     100 non-null    str
 2   段位      100 non-null    str
 3   LP      100 non-null    int64
 4   常用英雄    100 non-null    str
 5   等级      100 non-null    int64
 6   总场数     100 non-null    int64
 7   胜场      100 non-null    int64
 8   负场      100 non-null    int64
 9   胜率      100 non-null    str
dtypes: int64(6), str(4)
memory usage: 7.9 KB

,排名,召唤师,段位,LP,常用英雄,等级,总场数,胜场,负场,胜率
0,1,LOVE3001#lolxd,Challenger,1543,万花通灵/琴瑟仙女/牛头酋长,165,617,354,263,57%
1,2,Berik#haru,Challenger,1400,刀锋之影/傲之追猎者/破败之王,950,473,275,198,58%
2,3,TWITCH ELOSANTA#1111,Challenger,1400,死亡颂唱者/复仇焰魂/赏金猎人,550,363,214,149,59%
3,4,我依然是世一上#我不骗人,Challenger,1288,无双剑姬/机械公敌/铁血狼母,129,469,300,169,64%
4,5,Dun#NA1,Challenger,1242,奥术先驱/暗黑元首/惩戒之箭,539,520,296,224,57%

In [6]:
# 数据的选择
df["召唤师"]    # 获取召唤师列----> Series
df[["排名", "LP"]]    # 获取排名和LP列---->DataFrame
df[["排名", "LP"]]["LP"]    # 获取LP列---->Series
# 基于行号切片
df.iloc[0:4:2]    # 左闭右开
# 基于索引切片
df.loc[0:9:2]    # 闭区间

,排名,召唤师,段位,LP,常用英雄,等级,总场数,胜场,负场,胜率
0,1,LOVE3001#lolxd,Challenger,1543,万花通灵/琴瑟仙女/牛头酋长,165,617,354,263,57%
2,3,TWITCH ELOSANTA#1111,Challenger,1400,死亡颂唱者/复仇焰魂/赏金猎人,550,363,214,149,59%
4,5,Dun#NA1,Challenger,1242,奥术先驱/暗黑元首/惩戒之箭,539,520,296,224,57%
6,7,huncho#RANK1,Challenger,1199,铁血狼母/战争之影/法外狂徒,306,380,229,151,60%
8,9,EDG Viper#NA11,Challenger,1155,圣枪游侠/祖安花火/探险家,51,234,160,74,68%

In [7]:
# 将df赋值给df5,且索引为召唤师列
df_index_summoner = df.head(10).set_index('召唤师')
# # 不显示索引名字
# df_index_summoner.index.name = None

df_index_summoner.loc["LOVE3001#lolxd":"Feint#7993":2]

,排名,段位,LP,常用英雄,等级,总场数,胜场,负场,胜率
召唤师,,,,,,,,,
LOVE3001#lolxd,1,Challenger,1543,万花通灵/琴瑟仙女/牛头酋长,165,617,354,263,57%
TWITCH ELOSANTA#1111,3,Challenger,1400,死亡颂唱者/复仇焰魂/赏金猎人,550,363,214,149,59%
Dun#NA1,5,Challenger,1242,奥术先驱/暗黑元首/惩戒之箭,539,520,296,224,57%
huncho#RANK1,7,Challenger,1199,铁血狼母/战争之影/法外狂徒,306,380,229,151,60%
EDG Viper#NA11,9,Challenger,1155,圣枪游侠/祖安花火/探险家,51,234,160,74,68%

In [8]:
# 数据筛选
df[((df['胜场'] / df['总场数']) >= 0.6) & (df['LP'] >= 1000)]
df[df['排名'].between(10, 20)]   # 包含10和20
# df[df['排名'].isin(range(10, 20))]    # 不包含20

,排名,召唤师,段位,LP,常用英雄,等级,总场数,胜场,负场,胜率
9,10,Feint#7993,Challenger,1130,不破之誓/探险家/戏命师,747,926,464,462,50%
10,11,dusklol#000,Challenger,1126,元素女皇/虚空掠夺者/德玛西亚皇子,489,231,162,69,70%
11,12,Deoxys#Lotus,Challenger,1125,刀锋舞者/虚空之眼/离群之刺,406,308,171,137,56%
12,13,胖小海#na2,Challenger,1122,暗裔剑魔/法外狂徒/百裂冥犬,112,421,230,191,55%
13,14,was#10000,Challenger,1120,放逐之刃/离群之刺/影流之主,437,396,219,177,55%
14,15,PENGUIN L#NA1,Challenger,1110,愁云使者/冰霜女巫/铸星龙王,483,405,244,161,60%
15,16,mrbleetoe#ryann,Challenger,1108,猩红收割者/不屈之枪/奥术先驱,870,420,249,171,59%
16,17,Bad Apple#2nd,Challenger,1097,虚空女皇/影流之镰/离群之刺,165,839,468,371,56%
17,18,vem#iwnl,Challenger,1093,炼金术士/魔法猫咪/迅捷斥候,66,129,88,41,68%
18,19,ScrubNoob#Red,Challenger,1084,傲之追猎者/龙血武姬/永恒梦魇,143,280,184,96,66%
19,20,never wipe#mybut,Challenger,1078,放逐之刃/沙漠皇帝/离群之刺,253,251,146,105,58%

In [9]:
# 数据清洗
# 缺失值,重复值,异常值,数据一致性

# 1. 缺失值
df.isnull()
# 1.1 缺失值统计
df.isnull().sum()
# 1.2 删除缺失值
df.dropna()         # 行删除    修改后的数据作为返回值
df.dropna(axis=1)   # 列删除 默认值为0，表示行删除
# 1.3 填充缺失值
df.fillna(0)        # 填充0
df.ffill()          # 前向填充_用上一行的值填充缺失值
df.bfill()          # 后向填充_用下一行的值填充缺失值


# 2. 重复值
df.duplicated()     # 默认判断所有列数据是否重复
df.duplicated(subset=['LP'])  # 只判断LP列数据是否重复  # subset 用于指定要判断的列
# 2.1 删除重复值
# 可选参数keep:'first'(默认:保留第一个重复值),False(删除所有重复值),'last'(保留最后一个重复值)
df.drop_duplicates(subset=['召唤师'], keep=False)

,排名,召唤师,段位,LP,常用英雄,等级,总场数,胜场,负场,胜率
0,1,LOVE3001#lolxd,Challenger,1543,万花通灵/琴瑟仙女/牛头酋长,165,617,354,263,57%
1,2,Berik#haru,Challenger,1400,刀锋之影/傲之追猎者/破败之王,950,473,275,198,58%
2,3,TWITCH ELOSANTA#1111,Challenger,1400,死亡颂唱者/复仇焰魂/赏金猎人,550,363,214,149,59%
3,4,我依然是世一上#我不骗人,Challenger,1288,无双剑姬/机械公敌/铁血狼母,129,469,300,169,64%
4,5,Dun#NA1,Challenger,1242,奥术先驱/暗黑元首/惩戒之箭,539,520,296,224,57%
...,...,...,...,...,...,...,...,...,...,...
95,96,cyw#NA1,Challenger,828,虚空之眼/皮城女警/潮汐海灵,461,218,139,79,64%
96,97,Boybebui#NA1,Challenger,827,翠神/探险家/唤潮鲛姬,53,252,160,92,63%
97,98,宿命敲#lumi,Challenger,826,暴走萝莉/探险家/皮城女警,106,206,125,81,61%
98,99,Flow#THZ,Challenger,826,发条魔灵/沙漠皇帝/冰晶凤凰,1141,587,308,279,52%
99,100,Omi#Brooo,Challenger,826,虚空之女/戏命师/探险家,362,331,198,133,60%

In [ ]:
# 3. 异常值-格式处理
# 3.1 查看异常值



df[df['召唤师'].str.contains('#')]
df[df['LP'] < 0]
# 3.2 删除异常值
df.drop(df[df['LP'] < 0].index)  # 可选参数 inplace=True 表示在原数据上进行修改
# # 3.3 修复异常值
temp = df[df['召唤师'].str.contains('#')]['召唤师'].str.split(
    '#', expand=True)  # expand=True 表示切分后返回一个DataFrame
if temp.empty == False:
    print('temp非空')
    df['召唤师'] = temp[0]
    insert_tag = df.columns.tolist().index('召唤师') + 1
    df.insert(insert_tag, '后缀', temp[1])
else:
    print('temp为空')

df.to_csv('Data/opgg_tier_adjustID.csv', index=False)
# 定义一个空的DataFrame
hero_temp = pd.DataFrame()
if hasattr(df['常用英雄'], 'str'):
    hero_temp = df['常用英雄'].str.split('/', expand=True)
if hero_temp.empty == False:
    print('hero_temp非空')
    df_hero = df.drop(columns=['常用英雄'])
    df_hero[[0, 1, 2]] = [None, None, None]
    insert_tag = df_hero.columns.tolist().index('段位')
    new_columns = df_hero.columns.tolist()
    new_columns = new_columns[:insert_tag] +new_columns[-3:]+ new_columns[insert_tag:-3:]
    df_hero = df_hero[new_columns]
    for i in range(len(new_columns)):
        if new_columns[i] in range(3):
            new_columns[i] = ('常用英雄', new_columns[i]+1)
        else:
            new_columns[i] = (new_columns[i], '')
    df_hero.columns = pd.MultiIndex.from_tuples(new_columns)
  
#     # df[[('常用英雄', '英雄2'),('常用英雄', '英雄3')]] = temp
#     # df.drop(columns=['常用英雄'], inplace=True)
    df_hero[[('常用英雄',1),('常用英雄',2),('常用英雄',3)]] = hero_temp
else:
    print('hero_temp为空')
# hero_temp.iloc[45:55:]


df_hero.fillna('无', inplace=True)
df_hero.to_csv('Data/opgg_tier_adjustHero.csv', index=False)
df_hero.loc[45:55:]

temp非空
hero_temp非空

    排名             召唤师     后缀   常用英雄                         段位   LP    等级  \
                                   1      2       3
45  46      Erick Dota  Erick   暮光星灵   流光镜影    魔蛇之拥  Challenger  923  1798
46  47             一猛一    剑 来   不屈之枪     岩雀     探险家  Challenger  922   129
47  48            Kers   Mint  未来守护者   暗夜猎手    冰晶凤凰  Challenger  921    53
48  49           BOROS   2ppl   无双剑姬  未来守护者   傲之追猎者  Challenger  920   609
49  50        CaptBear    NA1   暴怒骑士      无       无  Challenger  918   883
50  51           Yuu13    137   百裂冥犬   法外狂徒  德玛西亚皇子  Challenger  912   723
51  52        Trisend3    NA1   暗黑元首   发条魔灵    符文法师  Challenger  912   512
52  53  翻斗花园第一野区突破手牛爷爷  喊我一声爷   费德提克   荒漠屠夫    暗裔剑魔  Challenger  910   125
53  54       ttv usiex    dif   诡术妖姬   疾风剑豪    元素女皇  Challenger  909    80
54  55       Thanatoes    kr2  未来守护者   铁血狼母    荒漠屠夫  Challenger  908   221
55  56        iron man   7541   疾风剑豪   暗黑元首    正义巨像  Challenger  908    67

    总场数   胜场   负场   胜率

45  544  282  262  52%
46  436  248  188  57%
47  261  185   76  71%
48  845  442  403  52%
49  459  261  198  57%
50  485  274  211  56%
51  628  333  295  53%
52  127   80   47  63%
53  495  278  217  56%
54  526  307  219  58%
55  245  170   75  69%

In [11]:
# 数据排序与分组
# 排序语法:
# df.sort_values(by='列名', ascending=Fasle)
# 可选参数 ascending：False 表示降序排序,默认值为True
# by = 可以不写，直接写列名即可
df.sort_values('总场数', ascending=False)
# 多列排序(排序优先级，左高右低)
df.sort_values(by=['胜场', '负场'], ascending=[False, True])

# 分组语法:
# df.groupby('列名:分组依据')['列名：分组统计'].size()
# 统计方法：
# size()：统计每个分组的样本数量
# mean()：计算每个分组的均值
# median()：计算每个分组的中位数
# std()：计算每个分组的标准差
# var()：计算每个分组的方差
# max()：计算每个分组的最大值
# min()：计算每个分组的最小值
# sum()：计算每个分组的总和
# count()：计算每个分组的非缺失值数量
# agg(方法1,方法2,方法3...)：对每个分组应用多个统计方法
df.groupby('胜场',sort=False)[['排名', 'LP', '胜场', '负场', '总场数']].agg(['mean','sum'])

        排名           LP           胜场          负场         总场数
      mean  sum    mean   sum   mean  sum   mean  sum   mean   sum
胜场
354    1.0    1  1543.0  1543  354.0  354  263.0  263  617.0   617
275    2.0    2  1400.0  1400  275.0  275  198.0  198  473.0   473
214    3.0    3  1400.0  1400  214.0  214  149.0  149  363.0   363
300    4.0    4  1288.0  1288  300.0  300  169.0  169  469.0   469
296   21.0   42  1097.0  2194  296.0  592  232.5  465  528.5  1057
..     ...  ...     ...   ...    ...  ...    ...  ...    ...   ...
149   92.0   92   833.0   833  149.0  149   85.0   85  234.0   234
308   96.0  192   828.5  1657  308.0  616  245.0  490  553.0  1106
340   94.0   94   830.0   830  340.0  340  334.0  334  674.0   674
139   96.0   96   828.0   828  139.0  139   79.0   79  218.0   218
198  100.0  100   826.0   826  198.0  198  133.0  133  331.0   331

[86 rows x 10 columns]

In [ ]:
test_csv = pd.read_csv('Data/score.csv')
test_csv[['日期','成绩']]= None
temp = test_csv['试卷/日期\t数学'].str.split('\t',expand=True)
test_csv[['试卷/日期\t数学', '成绩']] = temp
temp = test_csv['试卷/日期\t数学'].str.split('（', expand=True)
test_csv[['试卷/日期\t数学', '日期']] = temp
test_csv.columns = ['试卷','日期','成绩']
test_csv['日期'] = test_csv['日期'].str.replace('）', '')
test_csv['日期'] = test_csv['日期'].str.replace('/', '-')
test_csv['日期'] = test_csv['日期'].str.replace('.', '-')
test_csv.to_csv('Data/score_format.csv', index=False)